version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: screenplay_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: screenplay
      POSTGRES_PASSWORD: screenplay_pass
      POSTGRES_DB: screenplay_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
